
################   redis 配置
spring:
  redis:
#    host: 192.168.241.245
#    port: 6379
    timeout: 50
    database: 1
    #spring 2.1以下不支持lettuce 需要使用jedis
    lettuce:
      pool:
        max-active: 200
        max-idle: 10
        max-wait: 1000
    #下面这个相当于redis主从
    cluster:
      nodes: 127.0.0.0:6379 ,127.0.0.1:6379
      #设置哨兵模式
    sentinel:
      nodes: 127.0.0.0:6379 ,127.0.0.1:6379
      master: mymaster
server:
  port: 8080
