
spring:
  redis:
    host: 192.168.241.245
    port: 6379
    timeout: 50
    database: 0
    lettuce:
      pool:
        max-active: 200
        max-idle: 10
        max-wait: 1000
        min-idle: 5
    #    jedis:
#      pool:
#        max-active : 200
#        max-wait : -1
#        max-idle : 10
#        min-idle : 0
    cluster:
      nodes: 127.0.0.0:6379 ,127.0.0.1:6379
      #设置哨兵模式
    sentinel:
      nodes: 127.0.0.0:6379 ,127.0.0.1:6379
      master: mymaster
server:
  port: 8080
