server:
  port:8088
spring:
  redis:
    database: 2
    host: 192.168.241.246
    #host: 39.108.97.163
    port: 6379
    password:
    jedis:
      pool:
        max-active: 200    # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1       #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10        # 连接池中的最大空闲连接
        min-idle: 0        # 连接池中的最小空闲连接
    lettuce:
      shutdown-timeout: 1000  # 连接超时时间（毫秒）
