spring:
  rabbitmq:
    host: 192.168.241.246
    port: 5672
    username: rabbitmq
    password: 123456
    #将下面的注释掉就是轮查分发模式，而后面就是公平分发模式
#    virtual-host: /
    publisher-confirms: true  #消息发送到交换机确认机制，是否确认回调
    publisher-returns: true   #消息发送到交换机确认机制，是否返回回调
    listener:
      simple:
        acknowledge-mode: auto    #自动应答ack auto   manual 手动跟新,设置auto，则就是公平分发
        concurrency: 1              #定义最小的消费者数量
        max-concurrency: 100       #定义最大的消费者数量
        retry:
          enabled: false          #是否支持重试
          #将自动应答模式关闭,即开启acknowledge机制
        prefetch: 2              #预读设置,prefetch默认是1，如果设置为0就是轮询模式;就是告诉同一时间将几个消息给消费者,
  #升级2.1.5之后会报错
  main:
    allow-bean-definition-overriding: true
server:
  port: 8081
